apiVersion: skaffold/v2beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: maurilioferreira/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
deploy:
  kubectl:
    manifests:
      - k8s/server-deployment.yaml